### ISSUE TITLE
Better error message for findMany "The column value was different from the model"

### ISSUE THREAD

**Issue by robmurtagh** [prisma/photonjs#214]
This is not a bug, but filing an issue for a potential usability improvement as advised by @divyenduz

I had the following issue:
* When running photon.foo.findOne({ where: { fooId: "..." }) on a sample of inputs, everything worked
* But running photon.foo.findMany() returned an error with `Reason: Error in connector: The column value was different from the model`

The error message was correct, but not very specific. The eventual problem for me was buried in the data there was a regular string in the `fooId` column which had schema: 

```
fooId      String       @map("uuid") @default(uuid()) @id
```

**Comment by divyenduz** [comment]
IIRC this issue is the following, the DB column type is string and it contains a UUID value as suggested by this type: `fooId      String       @map("uuid") @default(uuid()) @id`

For a `findOne` call on that invalid `UUID` the returned error is expected but for a `findMany` call the error doesn't tell which column(s)/value(s) have an issue. 

With this information, @pantharshit00 please treat this as a bug repro and share your findings.

**Comment by pantharshit00** [comment]
Hi,

Sorry for the late response. I was able to reproduce this in version `prisma2@2.0.0-preview-10, binary version: 1b0c271f14ca00606f56c93717e228fe48c5603c` but this has been fixed in the latest alpha `prisma2@2.0.0-alpha.178, binary version: c29a2b977d631657c87b1bd8e0e880c110844331`

I am closing this now. Please test this on your end using the latest alpha(`npm install -g prisma2@alpha`). If you still getting please reply here so that we can reopen this or create a new issue.
