### ISSUE TITLE
photonJs example where is  prisma.yml

### ISSUE THREAD

**Issue by andrewcodes404** [prisma/photonjs#52]
I'm following the instructions to a tee but it gets weird here

> After having updated the datamodel, you need to deploy the changes:

`prisma deploy`
> Note that this also invokes prisma generate (because of the post-deploy hook in prisma.yml) which regenerates the Prisma client in ./src/generated/prisma-client.

But i have no prisma.yml file? 
I also don't have a /generated/prisma.graphlql, when were these meant to be created? 

as this is prisma2 . should we not be using `prisma2 deploy` ??

**Comment by marcjulian** [comment]
Since prisma2 you only need one file for the configuration of the database and the data model, read more [here](https://www.prisma.io/blog/announcing-prisma-2-zq1s745db8i5#improved-datamodel-syntax--project-definition). Hence, `prisma.yml` is not needed anymore. 

`prisma2 deploy` is not an available command. If you have setup your `project.prisma` file with the DB configs and the data model you can run `prisma2 generate` to [generate photon](https://github.com/prisma/photonjs#3-generate-photon-js).

**Comment by matthewmueller** [comment]
Thanks @marcjulian for your response! 

Yes, Prisma 2 is a set of standalone tools for managing your data. There is no `prisma.yml` or `prisma2 deploy` right now. Prisma would be embedded in your app and deployed with your app.
