### ISSUE TITLE
Connection fails if module has been bundled via Parcel

### ISSUE THREAD

**Issue by EranSch** [prisma/photonjs#61]
Howdy!

First off—great work here. This project feels like a game changer. I'm so excited to be a part of it's evolution however possible. 

I've been experimenting with using Photon in a monorepo, and using parcel to bundle certain pages for deployment out to lambdas. As such, there are some path changes and other things that get moved around a bit in the process. 

When testing the package independently, Photon works as expected, however after the package contents get bundled into a singular file, it is no longer able to connect. 

My entry point for the package consuming Photon returns a promise with the connected `photon` object:

`index.ts`

```ts
import Photon from '@generated/photon'
import { inspect } from 'util';

function initPhoton(photonConfig: any = {}) {
  const photon = new Photon(photonConfig);
  return photon.connect()
    .then(() => {
      console.log('photon connected');
      return photon;
    })
    .catch(error => {
      console.error('photon connection error', error);
      console.log(inspect(photon, { depth: 3, colors: true }));
      return false;
    });
}

export default initPhoton;
export { default as Photon } from '@generated/photon';
```

The file above is compiled via `tsc` and consumed by other packages within the project.  I wrote a small test file within the same package to validate that it behaves as expected. This file simple imports the module as it is exported from the compiled artifact of the file above. 

`test.js`

```js
const initPhoton = require('./dist/index').default;

initPhoton()
  .then(photon => photon && photon.organizations.create({
    data: {
      access_token: '126', scope: '126', team_id: '126', team_name: '126', user_id: '126',
    },
  }))
  .then(console.log)
  .catch(console.error)
  .then(() => process.exit());
```

When I run the file above, via `node test.js`, it appears to execute as expected. Returning the entry as it is written to the database. 

However, if I bundle the the `test.js` file using the command below, invoking the same file no longer works.

```sh
 npx parcel build test.js --target node --bundle-node-modules -d testDist

node testDist/test.js
```

I've been having trouble determining an actual source of the connection error. The `connect()` promise usually rejects with a value of `1` however if I copy the `prisma` folder into the `testDist` directory, the `connectionPromise` rejects with:

```
{ Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:508:9)
    at t.default.start (/Users/eschoellhorn/Repos/praisely-slackbot/packages/praisely-data/testDist/test.js:50:110668)
    at y.start (/Users/eschoellhorn/Repos/praisely-slackbot/packages/praisely-data/testDist/test.js:50:21187)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3 errno: 'EACCES', code: 'EACCES', syscall: 'spawn' }
```

I have experimented with trying to alter the `cwd` prop for the engine to point to an existing `prisma` folder but haven't been able to affect much meaningful change. Happy to keep trying, but could use some pointers...

Thanks and, again, awesome work!!

**Comment by matthewmueller** [comment]
Hi @Swingline0!

Thanks for reaching out. This seems like a path issue to me. We rely on a binary being present at `@generated/photon`. 

Does it work without `--bundle-node-modules`?

**Comment by Swingline0** [comment]
Hey @matthewmueller, thanks for the reply!

That certainly makes sense given the context. 

I created two bundles—one with `--bundle-node-modules` and one without—in order to see if there's any sort of difference. 

In short, there doesn't seem to be much of a different and, in fact, the bundles appear identical regardless of the `--bundle-node-modules` flag. 

Interestingly, the `--experimental-scope-hoisting` flag results in a substantially smaller bundle and one that actually works in my limited test use cases. 

Here's my best attempt at a summary:

* **test-bundle.js** via `parcel build test.js --target node --bundle-node-modules`
* **test-nobundle.js** via `parcel build test.js --target node`

Both behave the same. When run from a subdirectory in the project fail, the `connectionPromise` rejecting with the value `1`. When run from the package root (adjacent to `node_modules` and `prisma`  directories) the `connectionPromise` rejects  with the following exception:

```
TypeError: Cannot read property 'on' of undefined
         at t.default.start ({{project-root}}/test-bundle.js:50:110791)
         at y.start ({{project-root}}/test-bundle.js:50:21187)
         at process._tickCallback (internal/process/next_tick.js:68:7)
         at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
         at startup (internal/bootstrap/node.js:283:19)
         at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Interestingly, this bundle:

* **test-esh.js** via `parcel build test.js --target node --experimental-scope-hoisting`

Works as expected regardless of the location it is evaluated from. Looking at the source from the bundle, it's no surprise it works, as the changes are fairly minimal:

```js
(function() {
    var a = {},
        c = a && a.__importDefault || function(o) {
            return o && o.__esModule ? o : {
                default: o
            }
        };
    Object.defineProperty(a, "__esModule", {
        value: !0
    });
    const d = c(require("@generated/photon")),
        e = require("util");

    function f(o = {}) {
        const t = new d.default(o);
        return t.connect().then(() => (console.log("photon connected"), t)).catch(o => (console.error("photon connection error", o), console.log(e.inspect(t, {
            depth: 3,
            colors: !0
        })), !1))
    }
    var b = f;
    a.default = b;
    var g = require("@generated/photon"),
        h = g.default;
    a.Photon = h;
    const i = b;
    i().then(e => e && e.organizations.create({
        data: {
            access_token: "126",
            scope: "126",
            team_id: "126",
            team_name: "126",
            user_id: "126"
        }
    })).then(console.log).catch(console.error).then(() => process.exit());
})(); 
```

**Comment by Swingline0** [comment]
Happy to try more to help here, by the way. I'm game for whatever!

**Comment by Swingline0** [comment]
Hey there, was just perusing the current issues and noticed this related issue: #119 

I wasn't sure if my issue is specific to the binary going missing but figured I'd note it anyway.

**Comment by divyenduz** [comment]
@EranSch Thanks, yes, the other issue indeed covers this now. I am closing this one specifically. The other issues defined what you need to do (copy binaries over) but now how. If this is an issue for you in anyway, please feel free to tag me on our slack (slack.prisma.io) or in a comment on the other issue. 

If you think that your issue is different from the other one, please write a comment on this issue and tag me. 

I am closing this one 🙏 
Thank you :)
