### ISSUE TITLE
`updateMany` should return count of updated records

### ISSUE THREAD

**Issue by nikolasburk** [prisma/photonjs#82]
I have this `User` model:

```groovy
model User {
  id: Int @id
  name: String
}
```

The `updateMany` method for this model has the following signature:

```ts
 updateMany<T extends UserUpdateManyArgs>(args: Subset<T, UserUpdateManyArgs>): 'select' extends keyof T ? PromiseLike<UserGetPayload<ExtractUserUpdateManyArgsSelect<T>>> : UserClient<User>;
```

This means I'm just getting a single `User` object back. It should return the number records that have been updated in the database.

The same problem seems to exist for `deleteMany`.

![image](https://user-images.githubusercontent.com/4058327/59192543-102ef400-8b83-11e9-8791-243b5869b88f.png)

**Comment by n1ru4l** [comment]
Postgres supports the `RETURNING` statement, wouldn't that be performant enough? Or will it not be included because MySQL has no equivalent? 

Disclaimer: I have no idea about the implementation details, just started looking at the examples and the blog post and wanted to check some of the issue when I saw this 😄 I am pretty hyped to test this stuff in a new project 👍

**Comment by tvvignesh** [comment]
@nikolasburk Hi there. I understand this is a closed issue. But, what if we cant to get the value of the updated records? Shouldn't there be a select or include to do that?

While I understand cound is done for performance reasons, but can't we have the updated records returned only when user explicitly asks for it?

Thanks.

**Comment by pantharshit00** [comment]
I guess you already opened an issue for this. Please follow https://github.com/prisma/photonjs/issues/394 for this now.
